version: '2'

services:
  unobtanium:
    extends:
      file: docker-compose.tmpl.yml
      service: unobtanium-base-mainnet

  unobtanium-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unobtanium-base-testnet

  addrindexrs_uno:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs_uno-base-mainnet

  addrindexrs_uno-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs_uno-base-testnet

  unoparty:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-mainnet
    links:
      - unobtanium
      - addrindexrs_uno

  unoparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-testnet
    links:
      - unobtanium-testnet
      - addrindexrs_uno-testnet

volumes:
  unobtanium-data:
  addrindexrs_uno-data:
  unoparty-data:
