version: '2'

services:
  unobtanium:
    extends:
      file: docker-compose.tmpl.yml
      service: unobtanium-base-mainnet

  unobtanium-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unobtanium-base-testnet

  addrindexrs_uno:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs_uno-base-mainnet

  addrindexrs_uno-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs_uno-base-testnet

  unoparty:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-mainnet
    links:
      - unobtanium
      - addrindexrs_uno

  unoparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unoparty-base-testnet
    links:
      - unobtanium-testnet
      - addrindexrs_uno-testnet

  mongodb:
    extends:
      file: docker-compose.tmpl.yml
      service: mongodb-base

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base

  armory-utxsvr:
    extends:
      file: docker-compose.tmpl.yml
      service: armory-utxsvr-base-mainnet
    links:
      - unobtanium

  armory-utxsvr-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: armory-utxsvr-base-testnet
    links:
      - unobtanium-testnet

  unoblock:
    extends:
      file: docker-compose.tmpl.yml
      service: unoblock-base-mainnet
    links:
      - unobtanium
      - unoparty
      - mongodb
      - redis
      - armory-utxsvr

  unoblock-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: unoblock-base-testnet
    links:
      - unobtanium-testnet
      - unoparty-testnet
      - mongodb
      - redis
      - armory-utxsvr-testnet

  unowallet:
    extends:
      file: docker-compose.tmpl.yml
      service: unowallet-base
    links:
      - redis
      - unoblock
      - unoblock-testnet

  xup-proxy:
    extends:
      file: docker-compose.tmpl.yml
      service: xup-proxy-base-mainnet
    links:
      - redis
      - unobtanium
      - unoparty

  xup-proxy-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: xup-proxy-base-testnet
    links:
      - redis
      - unobtanium-testnet
      - unoparty-testnet

volumes:
  unobtanium-data:
  addrindexrs_uno-data:
  unoparty-data:
  unoblock-data:
  mongodb-data:
  armory-data:
